### ISSUE TITLE
Narre's Multiworld - vrstva pozadí v 'Down the Frozen Cave'

### ISSUE THREAD

**Issue by Narre** [Cecflit/levels#2]
Rampouchy nejsou vidět.
(nemám po ruce notebook, takže to písu sem)

**Comment by Narre** [comment]
A taky není přeloženo 'This is a checkpoint'

**Comment by Hypernoot** [comment]
Tohle je uložovák, ráááááá, ráááááá, ráááááá!

**Comment by Narre** [comment]
Opraveno v betě 56 (Ano, napsal jsem tam 66, ale za to může překlep. Chci říct američani.)
